// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package store

import (
	"context"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (user_id, name, filename, gcs_path, mime_type, size_bytes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, filename, gcs_path, mime_type, size_bytes, created_at
`

type CreateAssetParams struct {
	UserID    string `json:"user_id"`
	Name      string `json:"name"`
	Filename  string `json:"filename"`
	GcsPath   string `json:"gcs_path"`
	MimeType  string `json:"mime_type"`
	SizeBytes int64  `json:"size_bytes"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.UserID,
		arg.Name,
		arg.Filename,
		arg.GcsPath,
		arg.MimeType,
		arg.SizeBytes,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Filename,
		&i.GcsPath,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAsset = `-- name: DeleteAsset :exec
DELETE FROM assets WHERE id = $1 AND user_id = $2
`

type DeleteAssetParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteAsset(ctx context.Context, arg DeleteAssetParams) error {
	_, err := q.db.Exec(ctx, deleteAsset, arg.ID, arg.UserID)
	return err
}

const getAsset = `-- name: GetAsset :one
SELECT id, user_id, name, filename, gcs_path, mime_type, size_bytes, created_at FROM assets WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetAssetParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetAsset(ctx context.Context, arg GetAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, arg.ID, arg.UserID)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Filename,
		&i.GcsPath,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getAssetsByUser = `-- name: GetAssetsByUser :many
SELECT id, user_id, name, filename, gcs_path, mime_type, size_bytes, created_at FROM assets WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetAssetsByUser(ctx context.Context, userID string) ([]Asset, error) {
	rows, err := q.db.Query(ctx, getAssetsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Filename,
			&i.GcsPath,
			&i.MimeType,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
