// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: automations.sql

package store

import (
	"context"
)

const createAutomation = `-- name: CreateAutomation :one
INSERT INTO automations (user_id, name, trigger_type, trigger_value, action_type, action_value, active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, name, trigger_type, trigger_value, action_type, action_value, active, created_at
`

type CreateAutomationParams struct {
	UserID       string  `json:"user_id"`
	Name         string  `json:"name"`
	TriggerType  string  `json:"trigger_type"`
	TriggerValue *string `json:"trigger_value"`
	ActionType   string  `json:"action_type"`
	ActionValue  string  `json:"action_value"`
	Active       bool    `json:"active"`
}

func (q *Queries) CreateAutomation(ctx context.Context, arg CreateAutomationParams) (Automation, error) {
	row := q.db.QueryRow(ctx, createAutomation,
		arg.UserID,
		arg.Name,
		arg.TriggerType,
		arg.TriggerValue,
		arg.ActionType,
		arg.ActionValue,
		arg.Active,
	)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TriggerType,
		&i.TriggerValue,
		&i.ActionType,
		&i.ActionValue,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAutomation = `-- name: DeleteAutomation :exec
DELETE FROM automations WHERE id = $1 AND user_id = $2
`

type DeleteAutomationParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteAutomation(ctx context.Context, arg DeleteAutomationParams) error {
	_, err := q.db.Exec(ctx, deleteAutomation, arg.ID, arg.UserID)
	return err
}

const getAutomationsByUser = `-- name: GetAutomationsByUser :many
SELECT id, user_id, name, trigger_type, trigger_value, action_type, action_value, active, created_at FROM automations WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetAutomationsByUser(ctx context.Context, userID string) ([]Automation, error) {
	rows, err := q.db.Query(ctx, getAutomationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Automation{}
	for rows.Next() {
		var i Automation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TriggerType,
			&i.TriggerValue,
			&i.ActionType,
			&i.ActionValue,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAutomationActive = `-- name: UpdateAutomationActive :exec
UPDATE automations SET active = $2 WHERE id = $1 AND user_id = $3
`

type UpdateAutomationActiveParams struct {
	ID     string `json:"id"`
	Active bool   `json:"active"`
	UserID string `json:"user_id"`
}

func (q *Queries) UpdateAutomationActive(ctx context.Context, arg UpdateAutomationActiveParams) error {
	_, err := q.db.Exec(ctx, updateAutomationActive, arg.ID, arg.Active, arg.UserID)
	return err
}
