// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package store

import (
	"context"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (user_id, name, secret_hash)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, secret_hash, agent_version, last_seen_at, created_at
`

type CreateDeviceParams struct {
	UserID     string `json:"user_id"`
	Name       string `json:"name"`
	SecretHash string `json:"secret_hash"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice, arg.UserID, arg.Name, arg.SecretHash)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.SecretHash,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = $1 AND user_id = $2
`

type DeleteDeviceParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteDevice(ctx context.Context, arg DeleteDeviceParams) error {
	_, err := q.db.Exec(ctx, deleteDevice, arg.ID, arg.UserID)
	return err
}

const getDevice = `-- name: GetDevice :one
SELECT id, user_id, name, secret_hash, agent_version, last_seen_at, created_at FROM devices WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDevice(ctx context.Context, id string) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.SecretHash,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceState = `-- name: GetDeviceState :one
SELECT device_id, is_online, display_mode, brightness, cpu_percent, mem_mb, temp_c, uptime_s, wifi_dbm, ip_address, updated_at FROM device_states WHERE device_id = $1 LIMIT 1
`

func (q *Queries) GetDeviceState(ctx context.Context, deviceID string) (DeviceState, error) {
	row := q.db.QueryRow(ctx, getDeviceState, deviceID)
	var i DeviceState
	err := row.Scan(
		&i.DeviceID,
		&i.IsOnline,
		&i.DisplayMode,
		&i.Brightness,
		&i.CpuPercent,
		&i.MemMb,
		&i.TempC,
		&i.UptimeS,
		&i.WifiDbm,
		&i.IpAddress,
		&i.UpdatedAt,
	)
	return i, err
}

const getDevicesByUser = `-- name: GetDevicesByUser :many
SELECT id, user_id, name, secret_hash, agent_version, last_seen_at, created_at FROM devices WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetDevicesByUser(ctx context.Context, userID string) ([]Device, error) {
	rows, err := q.db.Query(ctx, getDevicesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.SecretHash,
			&i.AgentVersion,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameDevice = `-- name: RenameDevice :one
UPDATE devices SET name = $1 WHERE id = $2 AND user_id = $3 RETURNING id, user_id, name, secret_hash, agent_version, last_seen_at, created_at
`

type RenameDeviceParams struct {
	Name   string `json:"name"`
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) RenameDevice(ctx context.Context, arg RenameDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, renameDevice, arg.Name, arg.ID, arg.UserID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.SecretHash,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const setDeviceOffline = `-- name: SetDeviceOffline :exec
UPDATE device_states SET is_online = FALSE, updated_at = NOW()
WHERE device_id = $1
`

func (q *Queries) SetDeviceOffline(ctx context.Context, deviceID string) error {
	_, err := q.db.Exec(ctx, setDeviceOffline, deviceID)
	return err
}

const updateDeviceLastSeen = `-- name: UpdateDeviceLastSeen :exec
UPDATE devices
SET last_seen_at = NOW(), agent_version = $2
WHERE id = $1
`

type UpdateDeviceLastSeenParams struct {
	ID           string  `json:"id"`
	AgentVersion *string `json:"agent_version"`
}

func (q *Queries) UpdateDeviceLastSeen(ctx context.Context, arg UpdateDeviceLastSeenParams) error {
	_, err := q.db.Exec(ctx, updateDeviceLastSeen, arg.ID, arg.AgentVersion)
	return err
}

const upsertDeviceState = `-- name: UpsertDeviceState :exec
INSERT INTO device_states (
    device_id, is_online, display_mode, brightness,
    cpu_percent, mem_mb, temp_c, uptime_s, wifi_dbm, ip_address, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW())
ON CONFLICT (device_id) DO UPDATE SET
    is_online    = EXCLUDED.is_online,
    display_mode = EXCLUDED.display_mode,
    brightness   = EXCLUDED.brightness,
    cpu_percent  = EXCLUDED.cpu_percent,
    mem_mb       = EXCLUDED.mem_mb,
    temp_c       = EXCLUDED.temp_c,
    uptime_s     = EXCLUDED.uptime_s,
    wifi_dbm     = EXCLUDED.wifi_dbm,
    ip_address   = EXCLUDED.ip_address,
    updated_at   = NOW()
`

type UpsertDeviceStateParams struct {
	DeviceID    string  `json:"device_id"`
	IsOnline    bool    `json:"is_online"`
	DisplayMode string  `json:"display_mode"`
	Brightness  int32   `json:"brightness"`
	CpuPercent  float64 `json:"cpu_percent"`
	MemMb       float64 `json:"mem_mb"`
	TempC       float64 `json:"temp_c"`
	UptimeS     int64   `json:"uptime_s"`
	WifiDbm     int32   `json:"wifi_dbm"`
	IpAddress   string  `json:"ip_address"`
}

func (q *Queries) UpsertDeviceState(ctx context.Context, arg UpsertDeviceStateParams) error {
	_, err := q.db.Exec(ctx, upsertDeviceState,
		arg.DeviceID,
		arg.IsOnline,
		arg.DisplayMode,
		arg.Brightness,
		arg.CpuPercent,
		arg.MemMb,
		arg.TempC,
		arg.UptimeS,
		arg.WifiDbm,
		arg.IpAddress,
	)
	return err
}
