// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Device struct {
	ID           string             `json:"id"`
	UserID       string             `json:"user_id"`
	Name         string             `json:"name"`
	SecretHash   string             `json:"secret_hash"`
	AgentVersion *string            `json:"agent_version"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt    time.Time          `json:"created_at"`
}

type DeviceState struct {
	DeviceID    string    `json:"device_id"`
	IsOnline    bool      `json:"is_online"`
	DisplayMode string    `json:"display_mode"`
	Brightness  int32     `json:"brightness"`
	CpuPercent  float64   `json:"cpu_percent"`
	MemMb       float64   `json:"mem_mb"`
	TempC       float64   `json:"temp_c"`
	UptimeS     int64     `json:"uptime_s"`
	WifiDbm     int32     `json:"wifi_dbm"`
	IpAddress   string    `json:"ip_address"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type SpotifyToken struct {
	UserID       string    `json:"user_id"`
	AccessToken  string    `json:"access_token"`
	RefreshToken string    `json:"refresh_token"`
	ExpiresAt    time.Time `json:"expires_at"`
	Scope        string    `json:"scope"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type User struct {
	ID          string    `json:"id"`
	Email       string    `json:"email"`
	Name        string    `json:"name"`
	AvatarUrl   string    `json:"avatar_url"`
	GoogleID    *string   `json:"google_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	IsActivated bool      `json:"is_activated"`
}
