// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queue.sql

package store

import (
	"context"
)

const clearQueue = `-- name: ClearQueue :exec
DELETE FROM queue_items WHERE user_id = $1
`

func (q *Queries) ClearQueue(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, clearQueue, userID)
	return err
}

const createQueueItem = `-- name: CreateQueueItem :one
INSERT INTO queue_items (user_id, title, source, duration_s, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, title, source, duration_s, position, created_at
`

type CreateQueueItemParams struct {
	UserID    string `json:"user_id"`
	Title     string `json:"title"`
	Source    string `json:"source"`
	DurationS *int32 `json:"duration_s"`
	Position  int32  `json:"position"`
}

func (q *Queries) CreateQueueItem(ctx context.Context, arg CreateQueueItemParams) (QueueItem, error) {
	row := q.db.QueryRow(ctx, createQueueItem,
		arg.UserID,
		arg.Title,
		arg.Source,
		arg.DurationS,
		arg.Position,
	)
	var i QueueItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Source,
		&i.DurationS,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteQueueItem = `-- name: DeleteQueueItem :exec
DELETE FROM queue_items WHERE id = $1 AND user_id = $2
`

type DeleteQueueItemParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteQueueItem(ctx context.Context, arg DeleteQueueItemParams) error {
	_, err := q.db.Exec(ctx, deleteQueueItem, arg.ID, arg.UserID)
	return err
}

const getQueueByUser = `-- name: GetQueueByUser :many
SELECT id, user_id, title, source, duration_s, position, created_at FROM queue_items WHERE user_id = $1 ORDER BY position ASC, created_at ASC
`

func (q *Queries) GetQueueByUser(ctx context.Context, userID string) ([]QueueItem, error) {
	rows, err := q.db.Query(ctx, getQueueByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueueItem{}
	for rows.Next() {
		var i QueueItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Source,
			&i.DurationS,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
