// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package store

import (
	"context"
)

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (user_id, name, cron, mode, active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, cron, mode, active, created_at
`

type CreateScheduleParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
	Cron   string `json:"cron"`
	Mode   string `json:"mode"`
	Active bool   `json:"active"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.UserID,
		arg.Name,
		arg.Cron,
		arg.Mode,
		arg.Active,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Cron,
		&i.Mode,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM schedules WHERE id = $1 AND user_id = $2
`

type DeleteScheduleParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteSchedule(ctx context.Context, arg DeleteScheduleParams) error {
	_, err := q.db.Exec(ctx, deleteSchedule, arg.ID, arg.UserID)
	return err
}

const getSchedulesByUser = `-- name: GetSchedulesByUser :many
SELECT id, user_id, name, cron, mode, active, created_at FROM schedules WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetSchedulesByUser(ctx context.Context, userID string) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, getSchedulesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Cron,
			&i.Mode,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheduleActive = `-- name: UpdateScheduleActive :exec
UPDATE schedules SET active = $2 WHERE id = $1 AND user_id = $3
`

type UpdateScheduleActiveParams struct {
	ID     string `json:"id"`
	Active bool   `json:"active"`
	UserID string `json:"user_id"`
}

func (q *Queries) UpdateScheduleActive(ctx context.Context, arg UpdateScheduleActiveParams) error {
	_, err := q.db.Exec(ctx, updateScheduleActive, arg.ID, arg.Active, arg.UserID)
	return err
}
