// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spotify.sql

package store

import (
	"context"
	"time"
)

const deleteSpotifyToken = `-- name: DeleteSpotifyToken :exec
DELETE FROM spotify_tokens WHERE user_id = $1
`

func (q *Queries) DeleteSpotifyToken(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteSpotifyToken, userID)
	return err
}

const getSpotifyToken = `-- name: GetSpotifyToken :one
SELECT user_id, access_token, refresh_token, expires_at, scope, created_at, updated_at FROM spotify_tokens WHERE user_id = $1
`

func (q *Queries) GetSpotifyToken(ctx context.Context, userID string) (SpotifyToken, error) {
	row := q.db.QueryRow(ctx, getSpotifyToken, userID)
	var i SpotifyToken
	err := row.Scan(
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.Scope,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSpotifyToken = `-- name: UpsertSpotifyToken :one
INSERT INTO spotify_tokens (user_id, access_token, refresh_token, expires_at, scope)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE
  SET access_token  = EXCLUDED.access_token,
      refresh_token = CASE
                          WHEN EXCLUDED.refresh_token = '' THEN spotify_tokens.refresh_token
                          ELSE EXCLUDED.refresh_token
                      END,
      expires_at    = EXCLUDED.expires_at,
      scope         = EXCLUDED.scope,
      updated_at    = NOW()
RETURNING user_id, access_token, refresh_token, expires_at, scope, created_at, updated_at
`

type UpsertSpotifyTokenParams struct {
	UserID       string    `json:"user_id"`
	AccessToken  string    `json:"access_token"`
	RefreshToken string    `json:"refresh_token"`
	ExpiresAt    time.Time `json:"expires_at"`
	Scope        string    `json:"scope"`
}

func (q *Queries) UpsertSpotifyToken(ctx context.Context, arg UpsertSpotifyTokenParams) (SpotifyToken, error) {
	row := q.db.QueryRow(ctx, upsertSpotifyToken,
		arg.UserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.Scope,
	)
	var i SpotifyToken
	err := row.Scan(
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.Scope,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
